### ISSUE TITLE
Erro ao executar

### ISSUE THREAD

**Issue by daffymarco** [humbertodias/neural-network-training-with-games#2]
Erro para executar os arquivos, não deveria estar pronto para executar?

![image](https://user-images.githubusercontent.com/16739752/64376650-c5dcd800-cff6-11e9-9178-6532a9b3238a.png)

**Comment by humbertodias** [comment]
../pig: not a directory 

Tente clonar diretamente, assim o link simbolico existirá.

git clone https://github.com/humbertodias/neural-network-training-with-games
cd neural-network-training-with-games
make run-dino

ou

ln -s pig-0.5.1 pig
