### ISSUE TITLE
Compilar

### ISSUE THREAD

**Issue by marvinsiq** [humbertodias/neural-network-training-with-games#4]
Cara vim parar aqui por conta do projeto do [JVictorDias](https://github.com/JVictorDias).
Estou tentando compilar o fonte no Linux. Utilizo o Ubuntu 18
Já instalei:

libsdl2-dev
libsdl2-ttf-dev
libsdl2-image-dev

Quando faço o make dá o seguinte erro:

`g++ main.cpp -g -I../pig `sdl2-config --cflags --libs` -lSDL2 -lSDL2_ttf -lSDL2_image -lpthread -lwebp -o main
In file included from ../pig/PIG_Pack.h:4:0,
                 from ../pig/PIG.h:7,
                 from main.cpp:19:
../pig/CMapaCaracteres.h: In constructor ‘CMapaCaracteres::CMapaCaracteres(char*, SDL_Renderer*, int, int, SDL_Color, int, SDL_Color)’:
../pig/CMapaCaracteres.h:30:66: warning: format ‘%s’ expects a matching ‘char*’ argument [-Wformat=]
             printf("Erro: arquivo de fonte (%s) nao localizado\n");
                                                                  ^
../pig/CMapaCaracteres.h:63:40: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         off->SalvarImagem(NOME_ARQ_TEMP);
                                        ^
../pig/CMapaCaracteres.h: In constructor ‘CMapaCaracteres::CMapaCaracteres(char*, SDL_Renderer*, int, int, char*, int, SDL_Color)’:
../pig/CMapaCaracteres.h:145:40: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         off->SalvarImagem(NOME_ARQ_TEMP);
                                        ^
../pig/CMapaCaracteres.h:164:40: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         off->SalvarImagem(NOME_ARQ_TEMP);
                                        ^
In file included from ../pig/PIG_Pack.h:10:0,
                 from ../pig/PIG.h:7,
                 from main.cpp:19:
../pig/CJogo.h: In constructor ‘CJogo::CJogo(char*, int)’:
../pig/CJogo.h:53:104: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
         fontes[0] = new CMapaCaracteres("../fontes/arial.ttf",renderer,36,ESTILO_NORMAL,BRANCO,0,BRANCO);
                                                                                                        ^
In file included from main.cpp:21:0:
Sprites.h: In function ‘void InicializarSpriteCano()’:
Sprites.h:27:55: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteCano.Objeto = CriarSprite("imagens/cano.bmp");
                                                       ^
Sprites.h: In function ‘void InicializarSpritesNeuronios()’:
Sprites.h:54:65: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteNeuronDesativado = CriarSprite("imagens/neuronio7.png");
                                                                 ^
Sprites.h:57:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteNeuronAtivado = CriarSprite("imagens/neuronio7.png");
                                                              ^
Sprites.h:60:46: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteLuz = CriarSprite("imagens/luz.png");
                                              ^
Sprites.h:62:49: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteSeta = CriarSprite("imagens/seta2.png");
                                                 ^
Sprites.h: In function ‘void InicializarSpriteChao()’:
Sprites.h:68:55: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteChao.Objeto = CriarSprite("imagens/chao.png");
                                                       ^
Sprites.h: In function ‘void InicializarSpriteNuvem()’:
Sprites.h:75:58: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteNuvem.Objeto = CriarSprite("imagens/nuvens.png");
                                                          ^
Sprites.h: In function ‘void InicializarSpritePredio()’:
Sprites.h:82:60: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpritePredio.Objeto = CriarSprite("imagens/predios.png");
                                                            ^
Sprites.h: In function ‘void InicializarSpriteArvore()’:
Sprites.h:89:60: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteArvore.Objeto = CriarSprite("imagens/arvores.png");
                                                            ^
Sprites.h: In function ‘void InicializarSpriteParaquedas()’:
Sprites.h:96:67: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     SpriteParaquedas.Objeto = CriarSprite("imagens/paraquedas.png");
                                                                   ^
main.cpp: In function ‘void ConfiguracoesIniciais()’:
main.cpp:312:33: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     CriarJanela("Flappy Bird", 0);
                                 ^
main.cpp:345:91: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     FontePequena        = CriarFonteNormal("../fontes/arial.ttf", 11, PRETO,      0, PRETO);
                                                                                           ^
main.cpp:346:91: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     Fonte               = CriarFonteNormal("../fontes/arial.ttf", 15, PRETO,      0, PRETO);
                                                                                           ^
main.cpp:347:91: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     FontePretaGrande    = CriarFonteNormal("../fontes/arial.ttf", 18, PRETO,      0, PRETO);
                                                                                           ^
main.cpp:348:91: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     FonteVermelha       = CriarFonteNormal("../fontes/arial.ttf", 15, VERMELHO,   0, PRETO);
                                                                                           ^
main.cpp:349:91: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     FonteAzul           = CriarFonteNormal("../fontes/arial.ttf", 15, AZUL,       0, PRETO);
                                                                                           ^
main.cpp:350:91: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     FonteAzulGrande     = CriarFonteNormal("../fontes/arial.ttf", 18, AZUL,       0, PRETO);
                                                                                           ^
/usr/bin/ld: não foi possível localizar -lwebp
collect2: error: ld returned 1 exit status
Makefile:14: recipe for target 'all' failed
make: *** [all] Error 1`

Alguma ideia de como resolver? Ta faltando instalar alguma coisa ?
Todos deram o mesmo problema
Para o projeto do DeepCar especificamente eu tive que instalar a libgsl-dev também.

**Comment by humbertodias** [comment]
https://github.com/humbertodias/neural-network-training-with-games/blob/master/README.md
![deps](https://user-images.githubusercontent.com/9255997/82472040-d7eca100-9ac7-11ea-8f46-4a1e35256a69.png)
