### ISSUE TITLE
Google Dino & Flappy Abre a janela mas não aparece nada...

### ISSUE THREAD

**Issue by crashangelbr** [humbertodias/neural-network-training-with-games#5]
Olá amigo, estou tentando compilar no Ubuntu bionic e quando abre a janela do Dinossauro ou do Harry não aparece nada... fica só a janela aberta congelada...

sabe se falta alguma dependência??

Valeu

**Comment by humbertodias** [comment]
Hi, Try to pull the last commit and compile it using a docker image.

`docker build . -t pig-compiler`

`docker run -v $(pwd):/home/docker -ti pig-compiler make all`

`docker run --net host -e "DISPLAY" \
-v "$HOME/.Xauthority:/home/docker/.Xauthority:rw" \
-v "$(pwd):/home/docker" \
pig-compiler \
make run-flappy`
